### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by CodeStarX** [bernaferrari/EmojiSlider#1]
Hi
what happen?

`Android resource compilation failed
Output:  .../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1802: error: duplicate value for resource 'attr/progress' with config ''.
.../app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:1802: error: resource previously defined here.`

**Comment by bernaferrari** [comment]
Hey! Sorry for the delay, I downloaded the zip and just tested here without any issue. What are you trying to do and which Android Studio version are you using?

**Comment by CodeStarX** [comment]
Hi
Thanks, my friend
Android Studio 3.2
I added EmojiSlider library in my project and I encountered this error.

**Comment by bernaferrari** [comment]
Thanks! It looks the attribute "progress" is conflicting with something
else. I'll update the string to something else (probably tomorrow) and let
you know.

**Comment by CodeStarX** [comment]
Thanks :)

**Comment by bernaferrari** [comment]
Please try 0.3.1 version.

**Comment by yomade1** [comment]
Yh even with version 0.3.1 the same error arises. 

While checking your values for the library, you didn't add a format for attribute 'bar_track_color'. Guess that were the problem is from
