### ISSUE TITLE
error: resource attr/bar_track_color (aka com.example.aboutdesign:attr/bar_track_color) not found.     

### ISSUE THREAD

**Issue by bibek-ranjan-saha** [bernaferrari/EmojiSlider#11]
C:\Users\Bibek\.gradle\caches\transforms-2\files-2.1\5703088ec2f62a38637768e1928c7d3f\jetified-emojislider-0.3.2\res\values\values.xml:13:5-39:25: AAPT: error: resource attr/bar_track_color (aka com.example.aboutdesign:attr/bar_track_color) not found.
    
i am constantly getting this error i am trying very hard to change but i change the text inside it and getting same error i also tried "invalidate cache and restart" 5-6 times please help me out

**Comment by anarghya-das** [comment]
Update this 
implementation 'com.bernaferrari.emojislider:emojislider:0.3.2'
to 
implementation 'com.bernaferrari.emojislider:emojislider:0.3.3'
and it should work!

**Comment by bernaferrari** [comment]
Thanks!
