### ISSUE TITLE
Documentation for java

### ISSUE THREAD

**Issue by arjunmohnot** [bernaferrari/EmojiSlider#4]
Hey dear! Nice work. I just want to ask if you can provide me sample app in java or some kind of documentation. I had seen under usage random example in Java. Still I'm facing problem to implement. How to customise with different attribute.  Forgive me if there is some work around already being done but I'm not able to see in your repository.

Regards,
Arjun Mohnot

**Comment by bernaferrari** [comment]
What are the issues you are facing? If you can provide a small sample of the issue I can figure out for you.

**Comment by arjunmohnot** [comment]
Thanks for your instant reply. 

<com.bernaferrari.emojislider.EmojiSlider
    android:id="@+id/slider"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"/>

I had put this piece of code in my XML file.
Than the java code that you had provided. My doubt and issue is that I'm not able to understand how to customise the seek bar with different emoji and value. Can you please make a small piece of code. 
I'm not able to understand how to put in the code that you had provided in Customization and Attributes section.

Regards

**Comment by bernaferrari** [comment]
Sorry for not answering before.

Here shows you how to customize via XML: 
https://github.com/bernaferrari/EmojiSlider/blob/6f645b139c545eada8fefea6759ea73b488fbf8b/app/src/main/res/layout/frag_main.xml#L124

And this is how you would change the emoji in Java:
```java
((EmojiSlider) view.findViewById(R.id.sliderv5)).setEmoji();
```

**Comment by arjunmohnot** [comment]
Thank you so much 😊
