### ISSUE TITLE
error: resource attr/bar_track_color not found

### ISSUE THREAD

**Issue by aaravgarg** [bernaferrari/EmojiSlider#6]
I have perfectly imported the emoji slider library in my app and implemented it. I have created an instance of it in a fragment file... When I compile my code it just gives me this error and tells me that it cannot find the app bar color resource... I tried to define the attribute manually but it doesn't seem to have any effect...
```
<com.bernaferrari.emojislider.EmojiSlider
                android:id="@+id/emoji_slider"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:bar_track_color="@color/colorPrimaryDark"/>
```
This is the errror I get after compiling my app...
```
Android resource linking failed
AAPT: C:\Users\Administrator\AndroidStudioProjects\MoodGo\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:6044: error: resource attr/bar_track_color (aka com.example.moodgo:attr/bar_track_color) not found.
error: failed linking references.
```

**Comment by bernaferrari** [comment]
Closed with https://github.com/bernaferrari/EmojiSlider/pull/10
